---

- name: Test if distribution is RedHat
  assert:
    that: >
      ansible_os_family == "RedHat"

- name: Install the YUM plugin package
  yum:
    name: "yum-{{ 'plugin-' if ansible_distribution_major_version | int >= 6 else '' }}{{ item.key }}"
    state: present
  with_dict: yum_plugin_config
  tags:
    - yum_plugin_pkg

- name: Configure the YUM plugin
  template:
    src: plugin.conf.j2
    dest: /etc/yum/pluginconf.d/{{ item.key }}.conf
  with_dict: yum_plugin_config
  tags:
    - yum_plugin_config
